- name: Deploy index.html into Nginx web server on Ubuntu
  template: src=index.html.j2 dest=/var/www/html/index.html
  when: ansible_distribution == "Ubuntu"
  notify:
    - Restart nginx server

- name: Deploy index.html into Nginx web server on CentOS 
  template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
  when: ansible_distribution == "CentOS"
  notify:
    - Restart nginx server
