- name: Install nginx in Ubuntu
  apt: name=nginx state=present update_cache=yes
  when: ( ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" )
  environment: "{{proxy_conf}}"

- name: Install epel-release package in CentOS
  yum: name=epel-release state=present
  when: ansible_os_family == "RedHat"
  environment: "{{proxy_conf}}"

- name: Install nginx in CentOS 
  yum: name=nginx state=present
  when: ansible_os_family == "RedHat"
  environment: "{{proxy_conf}}"
